
SET(Thirdparty_root "" CACHE PATH "The root of the VRPN_ROOT")


FIND_PATH(THIRDPARTY_INCLUDE_DIR x264.h
  PATH_SUFFIXES inc include Frameworks 
  HINTS
  ${PROJECT_SOURCE_DIR}/dependencies2015/win64
  ${PROJECT_SOURCE_DIR}/dependencies2017/win64
  ${Thirdparty_root}
  )
MARK_AS_ADVANCED(THIRDPARTY_INCLUDE_DIR)

MACRO(FIND_THIRDPARTY_LIBRARY MYLIBRARY MYLIBRARYNAME)  
  FIND_LIBRARY(${MYLIBRARY}
    NAMES ${MYLIBRARYNAME}
    PATH_SUFFIXES bin lib lib/x64 stage/lib lib64 build/lib64 Frameworks
    PATHS
	${PROJECT_SOURCE_DIR}/dependencies2015/win64
	${PROJECT_SOURCE_DIR}/dependencies2017/win64	
	${Thirdparty_root}
    )
  MARK_AS_ADVANCED(${MYLIBRARY})
ENDMACRO(FIND_THIRDPARTY_LIBRARY LIBRARY LIBRARYNAME)



SET(FFMPEG_AVCODEC_FOUND ON)

# Find release (optimized) libs

FIND_THIRDPARTY_LIBRARY(FFMPEG_AVCODEC_LIBRARY  avcodec)
FIND_THIRDPARTY_LIBRARY(FFMPEG_AVDEVICE_LIBRARY  avdevice)
FIND_THIRDPARTY_LIBRARY(FFMPEG_AVFILTER_LIBRARY  avfilter)
FIND_THIRDPARTY_LIBRARY(FFMPEG_AVUTIL_LIBRARY  avutil)
FIND_THIRDPARTY_LIBRARY(FFMPEG_AVFORMAT_LIBRARY  avformat)
FIND_THIRDPARTY_LIBRARY(FFMPEG_SWSCALE_LIBRARY  swscale)
FIND_THIRDPARTY_LIBRARY(FFMPEG_SWRESAMPLE_LIBRARY  swresample)

FIND_THIRDPARTY_LIBRARY(ZLIB_LIBRARY  zlib)
FIND_THIRDPARTY_LIBRARY(LIBCURL_LIBRARY  libcurl)
FIND_THIRDPARTY_LIBRARY(LIBx264_LIBRARY  x264)
FIND_THIRDPARTY_LIBRARY(FREETYPE_LIBRARY  freetype)

# Find debug libs
FIND_THIRDPARTY_LIBRARY(FFMPEG_AVCODEC_LIBRARY_DEBUG  avcodec)
FIND_THIRDPARTY_LIBRARY(FFMPEG_AVDEVICE_LIBRARY_DEBUG  avdevice)
FIND_THIRDPARTY_LIBRARY(FFMPEG_AVFILTER_LIBRARY_DEBUG  avfilter)
FIND_THIRDPARTY_LIBRARY(FFMPEG_AVUTIL_LIBRARY_DEBUG  avutil)
FIND_THIRDPARTY_LIBRARY(FFMPEG_AVFORMAT_LIBRARY_DEBUG  avformat)
FIND_THIRDPARTY_LIBRARY(FFMPEG_SWSCALE_LIBRARY_DEBUG  swscale)
FIND_THIRDPARTY_LIBRARY(FFMPEG_SWRESAMPLE_LIBRARY_DEBUG  swresample)

FIND_THIRDPARTY_LIBRARY(ZLIB_LIBRARY_DEBUG  zlib)
FIND_THIRDPARTY_LIBRARY(LIBCURL_LIBRARY_DEBUG  libcurl)
FIND_THIRDPARTY_LIBRARY(LIBx264_LIBRARY_DEBUG  x264)
FIND_THIRDPARTY_LIBRARY(FREETYPE_LIBRARY_DEBUG  freetype)
